---
services:
  backend:
    build: ./backend
    ports: [8081:81]
    environment: [PORT=81]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes: [./nginx.conf:/etc/nginx/conf.d/default.conf:ro]
    ports: [8080:80]
