---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backendImage }}:{{ .Values.backendVersion }}
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fullstack-app
spec:
  selector:
    app.kubernetes.io/name: backend
  {{- if or .Values.enabledFeatures.metrics .Values.enabledFeatures.logging }}
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30083
  {{- else }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  {{- end }}
